apply plugin: "java"

sourceSets.main.java.srcDirs = ["src"]

repositories{
    mavenCentral()

    //Downloads the dependencies JAR file from Mindustry releases; does not use any real repository. Surprisingly, this is the most reliable option.
    ivy{
        url = 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/download/[revision]/dependencies.jar'}
        metadataSources{ artifact() }
    }

    //If the version is set to 'latest', downloads the latest Mindustry *release* as a dependency
    ivy{
        url = 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/[revision]/download/dependencies.jar'}
        metadataSources{ artifact() }
    }

    //For depending on the absolute newest commit for Mindustry
    ivy{
        url = 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/download/master/[revision].jar'}
        metadataSources{ artifact() }
    }
}

java{
    targetCompatibility = JavaVersion.VERSION_17
    sourceCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

ext{
    // Mindustry version to depend on.
    // Valid values:
    // - latest: depend on the latest release of mindustry
    // - be: depend on the very latest commit of mindustry
    // - v<number>: depend on a specific commit
    mindustryVersion = "v159.7"
    isWindows = System.getProperty("os.name").toLowerCase().contains("windows")
    sdkRoot = System.getenv("ANDROID_HOME") ?: System.getenv("ANDROID_SDK_ROOT")

    mindustryJar = "E:/project/MindustryModDevLib/Mindustry8.0.jar"
    steamModsDir = "E:/Steam/steamapps/common/Mindustry/saves/mods"
    appDataModsDir = "${System.getenv('APPDATA')}/Mindustry/mods"
    modDeployName = "SpaceIndustryModJar.jar"
}

dependencies{
    compileOnly mindustryVersion == "be" ? "Anuken:MindustryBuilds:latest" : "Anuken:Mindustry:$mindustryVersion"
}

tasks.register('jarAndroid'){
    dependsOn "jar"
    def projectName = project.name

    doLast{
        if(!sdkRoot || !new File(sdkRoot).exists()) throw new GradleException("No valid Android SDK found. Ensure that ANDROID_HOME is set to your Android SDK directory.")

        def platformRoot = new File("$sdkRoot/platforms/").listFiles().sort().reverse().find{ f -> new File(f, "android.jar").exists() }

        if(!platformRoot) throw new GradleException("No android.jar found. Ensure that you have an Android platform installed.")

        //collect dependencies needed for desugaring
        def dependencies = (configurations.compileClasspath.asList() + configurations.runtimeClasspath.asList() + [new File(platformRoot, "android.jar")]).collect{ "--classpath $it.path" }.join(" ")

        def d8 = isWindows ? "d8.bat" : "d8"

        //dex and desugar files - this requires d8 in your PATH
        "$d8 $dependencies --min-api 21 --output ${projectName}Android.jar ${projectName}Desktop.jar"
                .execute(null, new File("build/libs")).waitForProcessOutput(System.out, System.err)
    }
}

jar{
    archiveFileName = "${project.name}Desktop.jar"

    from{
        configurations.runtimeClasspath.collect{ it.isDirectory() ? it : zipTree(it) }
    }

    from(projectDir){
        include "mod.hjson"
    }

    from("assets/"){
        include "**"
    }
}

tasks.register('deploy', Jar){
    def projectName = project.name
    dependsOn jarAndroid
    dependsOn jar
    archiveFileName = "${projectName}.jar"

    from{ [zipTree("build/libs/${projectName}Desktop.jar"), zipTree("build/libs/${projectName}Android.jar")] }

    doLast{
        delete{
            delete "build/libs/${projectName}Android.jar"
        }
    }
}

tasks.register('copyTo') {
    dependsOn jar

    doLast {
        [steamModsDir, appDataModsDir].each { dest ->
            copy {
                from jar.archiveFile
                into dest
                rename { modDeployName }
            }
        }
    }
}

tasks.register('debugMobile', JavaExec) {
    dependsOn 'copyTo'

    classpath = files(mindustryJar)
    mainClass = 'mindustry.desktop.DesktopLauncher'
    args = [
            //"-debug",
            "-testMobile"
    ]
}

tasks.register('debugDesktop', JavaExec) {
    dependsOn 'copyTo'

    classpath = files(mindustryJar)
    mainClass = 'mindustry.desktop.DesktopLauncher'
    args = [
            //"-debug",
    ]
}

tasks.register('debugBE', JavaExec) {
    dependsOn 'copyTo'

    classpath = files(mindustryBEJar)
    mainClass = 'mindustry.desktop.DesktopLauncher'
    args = [
            //"-debug",
    ]
}
